### ISSUE TITLE
Allow a set of new certificates to be generated for a given custom CA.

### ISSUE THREAD

**Issue by lgarron** [google/badssl.com#10]
Unfortunately, I can't share the server private key on GitHub, because it's being used for tests that should probably not be MitM-able. And it will become more difficult to obtain publicly signed SHA-1 certs in the near future.

However, it might be useful to use OpenSSL to generate:

- a custom CA
- a server key
- a CSR for *.badssl.com (or maybe `localhost`?)
- [certs used by badssl](https://github.com/lgarron/badssl.com/tree/master/certs) signed by the CA

... and then provide a way to run that locally for development. (Strawman for getting the same cert behaviour as public certs, even though it would make me uncomfortable: throw away the CA key after signing certs, import the CA key into the trust store, modify `etc/hosts` to point the desired test domain to `localhost`.)

https://github.com/edvinanet/tls-o-matic does something similar, so their code might be useful to look at.

**Comment by lgarron** [comment]
For the current `*.badssl.com` certs, I used the following:
        
    function gencsr() {
    echo "
    [ req ]
    default_bits        = 2048
    default_keyfile     = badssl-wildcard.key
    distinguished_name  = req_distinguished_name
    
    [ req_distinguished_name ]
    countryName           = Country Name (2 letter code)
    countryName_default   = US
    stateOrProvinceName   = State or Province Name (full name)
    stateOrProvinceName_default = California
    localityName          = Locality Name (eg, city)
    localityName_default  = San Francisco
    organizationName          = Organization Name (eg, company)
    organizationName_default  = BadSSL
    commonName            = Common Name (eg, YOUR name)
    commonName_default  = *.badssl.com
    commonName_max        = 64
    " > badssl.conf
    
    openssl genrsa -aes128 -out "badssl.key" 2048
    
    openssl req -new -key "badssl.key" -out "badssl.csr" -config "badssl.conf"
    }
    
    gencsr


Note that this relies on the CA to add the SAN (with the root registered domain `badssl.com`) when providing a signed cert.

**Comment by marumari** [comment]
Can't youtube use naughtyssl.com or something?  :P

Anyways, I'll try to see if I can scrounge up some time this weekend to throw together a shell script or something.  Note to myself: make sure to write up something to do some minor modifications to the primary page to create a link to download the root certs, when going this route.

**Comment by marumari** [comment]
I've got most of them generated:
- Root Certificate
- Intermediate Certificate
- Normal Wildcard
- Expired Wildcard
- SHA-1 (2016)
- SHA-1 (2017)

I'll work on the rest of them tomorrow, and hopefully get some kind of pull request going over the next day or so.

**Comment by marumari** [comment]
Although I'll probably upload all root CA, intermediate CA, wildcard certs, and key for the wildcart certs, I think it's best to not upload the key for the root/intermediate CA.  I'd hate for someone to add the root CA to their trust store, only to find themselves getting completely owned sometime in the future.

**Comment by riking** [comment]
Another possibility would be to manage it using CFSSL - https://blog.cloudflare.com/introducing-cfssl/ https://github.com/cloudflare/cfssl

**Comment by lgarron** [comment]
CFSSL sounds nice, although it's unclear if their focus on strong security wouldn't allow our use cases. Given that @marumari's script is already written and pretty much works everywhere (using only `openssl` and `bash`), I'd rather keep that.

**Comment by lgarron** [comment]
b02f505f02c31c937f9e69751956bd647ebdb941 handles this like a champ.
