### ISSUE TITLE
Auto-generate a list of `/etc/hosts` domains

### ISSUE THREAD

**Issue by lgarron** [google/badssl.com#102]
From #100:

> If possible, I think a decent solution for now would be for jekyll to generate a list of subdomains at, say `badssl.com/hosts`.

This would go well with #101 to help local development.

**Comment by lgarron** [comment]
Man, we have a *lot* of duplicate issues. :-P

See #179 174 for this.

**Comment by marumari** [comment]
Why have just one issue when you could have two and have twice the fun?
