### ISSUE TITLE
Move `.pem` files from certs/ to certs/cert-chains

### ISSUE THREAD

**Issue by lgarron** [google/badssl.com#124]
Right now, they show up in the same folder as some other stuff that makes everything really confusing:

- `.gitignore`
- `cert-generator`
- `foreign`
- `self-signed`

**Comment by Hoverbear** [comment]
I'll work on this after finals are over (monday)!

**Comment by lgarron** [comment]
As of b02f505f02c31c937f9e69751956bd647ebdb941, chains are in `certs/gen/chains`
