### ISSUE TITLE
Figure out why `superfish` and `dsdtestprovider` are triggering non-overridable interstitials in Chrome

### ISSUE THREAD

**Issue by lgarron** [google/badssl.com#125]
https://superfish.badssl.com/
https://dsdtestprovider.badssl.com/

**Comment by lgarron** [comment]
By contrast, I can load https://edellroot.badssl.com/
![screen shot 2015-12-03 at 18 51 13](https://cloud.githubusercontent.com/assets/248078/11580700/d80e3f2e-99ee-11e5-8cfd-3a760a350ae4.png)

**Comment by Hoverbear** [comment]
Seems to be working fine for me in chromium.

![screenshot from 2015-12-04 09-05-58](https://cloud.githubusercontent.com/assets/130903/11595828/451ad74a-9a66-11e5-9802-ce706f286dbc.png)

**Comment by lgarron** [comment]
Pointed out by @davidben: The Basic Constraints extension for our leaf cert marks it as a CA.

<img width="799" alt="screen shot 2016-01-05 at 14 47 25" src="https://cloud.githubusercontent.com/assets/248078/12129865/420eaca2-b3bb-11e5-8c18-59c0982ee625.png">

**Comment by sleevi** [comment]
And CRLSets.
