### ISSUE TITLE
Do not rely on SNI in client

### ISSUE THREAD

**Issue by lordmauve** [google/badssl.com#146]
If SNI support is not present in the client code, then the certificate received for every domain is the valid `*.badssl.com` wildcard certificate.

This can give very misleading results.

To address this so that the individual certificates can be received by clients without SNI support, each domain would need to be hosted on a separate IP address.

An alternative would be to use Nginx's `$ssl_server_name` to detect when SNI is not in use and warn the user that checks will be invalid:

http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables

**Comment by lgarron** [comment]
Thanks for the suggestion!
> To address this so that the individual certificates can be received by clients without SNI support, each domain would need to be hosted on a separate IP address.

Indeed, separate IP addresses would be prohibitive (although we are considering separate ports).

> An alternative would be to use Nginx's $ssl_server_name to detect when SNI is not in use and warn the user that checks will be invalid:

Is there a performance penalty for this?

**Comment by lordmauve** [comment]
> Is there a performance penalty for this?

Practically nil. The SNI will already have happened during the TLS handshake, so all this requires is for nginx to compare the `$ssl_server_name` to `$server_name` and redirect to a "SNI unavailable" page if they do not match.

**Comment by robmoss2k** [comment]
I've just fallen over this one trying to test IE6 and IE8 on Windows XP SP3 - any chance you could split the ports out, at least for older clients?

**Comment by lgarron** [comment]
This just struck again:
- https://blog.sucuri.net/2016/03/beware-unverified-tls-certificates-php-python.html
- https://lukasa.co.uk/2016/04/In_Response_To_Sucuri/

badssl.com is a background project for me, but I want to address this in Q2 (i.e. by June).

**Comment by marumari** [comment]
Me too, I wish it was a dedicated main project for me.  It really should be for one of us, given how important it seems to be coming.

**Comment by Hoverbear** [comment]
So we could do this with different ports instead of IP addresses? I think we could automate the port assigning via Jekyll's templating.

**Comment by lgarron** [comment]
I would prefer to avoid using ports, since that will conflate port number display with other details. I think we should just fail if the user doesn't have SNI.

**Comment by marumari** [comment]
I don't think there's anyway to force nginx to drop a connection if there's
no SNI, is there? It pretty persistently wants to serve you something.

On Apr 8, 2016, at 1:54 PM, Lucas Garron <notifications@github.com> wrote:

I would prefer to avoid using ports, since that will conflate port number
display with other details. I think we should just fail if the user doesn't
have SNI.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/lgarron/badssl.com/issues/146#issuecomment-207555640>

**Comment by glyph** [comment]
Just another data point here, users trying to [validate their Emacs TLS configs](https://glyph.twistedmatrix.com/2015/11/editor-malware.html) are running across this due to the lack of SNI in surprisingly recent (although not current) versions of GnuTLS.

**Comment by Hoverbear** [comment]
That's an awesome use of the site, thanks for sharing that.

**Comment by lgarron** [comment]
> Practically nil. The SNI will already have happened during the TLS handshake, so all this requires is for nginx to compare the $ssl_server_name to $server_name and redirect to a "SNI unavailable" page if they do not match.

I looked into it, and it seems `$ssl_server_name` requires nginx 1.7, which is still mainline, and not available for our Ubuntu 14.10 server: http://nginx.org/en/linux_packages.html#distributions

Nothing insurmountable, but I don't feel like *even more* yak shaving right now. :-/

**Comment by lgarron** [comment]
> nginx 1.7, which is still mainline

Wait, it seems nginx is up to 1.9 for mainline now. Our `apt-get` sources were just really out of date.

**Comment by Hoverbear** [comment]
Woo!

**Comment by glyph** [comment]
> That's an awesome use of the site, thanks for sharing that.

Thanks for providing such a great resource :).

**Comment by lgarron** [comment]
(Sorry for the update spam. I was trying to different stuff to get `nginx` to work.)

**Comment by lgarron** [comment]
I think our current solution works alright.
