### ISSUE TITLE
Can't build badssl.com

### ISSUE THREAD

**Issue by jonathanKingston** [google/badssl.com#157]
Hey I'm likely doing something silly, however so I don't forget I wanted to file the bug.

So I ran:
```
make jekyll
```
I got the following:
```
./_site/certs/cert-generator/cert-self-signed-symlink-generator.sh # Generate symlinks to self-signed for everything that doesn't exist in certs
ls: cannot access self-signed: No such file or directory
```

Also should Jekyll be in the prerequisites and install step? Perhaps I'm missing a step here.
Thanks

**Comment by Hoverbear** [comment]
Hi there!

It looks like that's a bug! #156 fixes this.

Typically I build using docker which involves executing something like this:

```bash
sudo docker rm -f badssl | true && make docker && sudo docker run -ti -p 80:80 -p 443:443 --name badssl badssl
```

Then you can add the various domains to your `/etc/hosts` file:

```
127.0.0.1      badssl.com
127.0.0.1      www.badssl.com
127.0.0.1      expired.badssl.com
127.0.0.1      wrong.host.badssl.com
127.0.0.1      self-signed.badssl.com
127.0.0.1      incomplete-chain.badssl.com
127.0.0.1      sha1.badssl.com
127.0.0.1      mixed.badssl.com
127.0.0.1      rc4.badssl.com
127.0.0.1      cbc.badssl.com
127.0.0.1      hsts.badssl.com
127.0.0.1      preloaded-hsts.badssl.com
127.0.0.1      sha1-2016.badssl.com
127.0.0.1      sha1-2017.badssl.com
127.0.0.1      broken-diffie-hellman.badssl.com
127.0.0.1      weak-diffie-hellman.badssl.com
127.0.0.1      rsa512.badssl.com
127.0.0.1      rsa1024.badssl.com
127.0.0.1      rsa8192.badssl.com
127.0.0.1      ecc.badssl.com
127.0.0.1      sha256.badssl.com
127.0.0.1      dh480.badssl.com
127.0.0.1      dh512.badssl.com
127.0.0.1      dh1024.badssl.com
127.0.0.1      dh2048.badssl.com
127.0.0.1      http.badssl.com
127.0.0.1      dh-small-subgroup.com
127.0.0.1      dh-composite.badssl.com
127.0.0.1      mozilla-modern.badssl.com
127.0.0.1      mozilla-intermediate.badssl.com
127.0.0.1      mozilla-old.badssl.com
127.0.0.1      edellroot.badssl.com
127.0.0.1      superfish.badssl.com
127.0.0.1      dsdtestprovider.badssl.com
```

**Comment by jonathanKingston** [comment]
Thanks @Hoverbear that branch certainly fixes the build issues thanks however none of the certs it made are of an unknown issuer is it expected to add a CA to the browser?

**Comment by marumari** [comment]
You should be able to access the root cert to install at this URL:

http://http.badssl.com/certs/badssl-root.pem

**Comment by lgarron** [comment]
Hopefully `make test` should just work now. Feel free to file a new bug if you still run into issues.

**Comment by lgarron** [comment]
I'm gonna close this one to avoid keeping it in the issue list.

The [setup instructions](https://github.com/google/badssl.com#testing-and-development) should hopefully "just work" now. Feel free to start a new bug if you can't get things working.
