### ISSUE TITLE
Our setup process is broken. :-(

### ISSUE THREAD

**Issue by lgarron** [google/badssl.com#162]
I tried for an hour to fix it on the weekend, and couldn't.
I don't recall if 14.04 still worked, but I couldn't get the Docker command working on 15.10.

(This is one reason why progress on #159 is so slow; I don't know how to dig us back out.)

**Comment by Hoverbear** [comment]
Lucas, can you tell me which branch and command you were running?

Currently the "right" way is to use the `data` branch sitting in my Pull Request and running:

```bash
sudo docker rm -f badssl | true && ;2Cmake docker && sudo docker run -ti -p 80:80 -p 443:443 --name badssl badssl 
```

If I recall master doesn't work very well right now.

**Comment by Hoverbear** [comment]
@lgarron I checked on this today and you're right. An update in one of the Jekyll dependencies broke Jekyll on Ubuntu:14.04 since it's only running Ruby 2.0. :(

**Comment by lgarron** [comment]
> We could select a new base image if wanted.

I tried moving to 15.10, but had trouble getting the dependencies working. Howzabout 16.04? :-P

**Comment by Hoverbear** [comment]
I thin 16.04 is preferable to 15.10. Want me to work on this migration?

**Comment by lgarron** [comment]
If you could get the Docker command working on Ubuntu 16.04, that would be awesome! I'm blocked on my work here unless I can get that working.

**Comment by Hoverbear** [comment]
I confirmed 16.04 supports Ruby 2.3 which will work. Will make a PR in the next week!

**Comment by lgarron** [comment]
Thanks to our new cert generation (b02f505f02c31c937f9e69751956bd647ebdb941) and improvements in Docker, this is now much smoother. We have a bit to go, though.

**Comment by lgarron** [comment]
19d2ace3fb47f810436e4a40d478e9f7fd9906bd is not perfect, but I think we're at the point where testing and deployment is not fragile anymore.
