### ISSUE TITLE
Upgrade test is incorrect -- link on index.html points to HTTPS version

### ISSUE THREAD

**Issue by obi1kenobi** [google/badssl.com#169]
![screen shot 2016-06-08 at 2 48 13 pm](https://cloud.githubusercontent.com/assets/2348618/15906718/1407a5b0-2d88-11e6-8671-bca035a1dad2.png)

If I understand things correctly, the upgrade test should ensure that insecure requests get upgraded to HTTPS. For that to be tested, the original link should be to the HTTP version of the page. However, the link currently points to the HTTPS version of the page, and is able to give false positives.

**Comment by lgarron** [comment]
`upgrade-insecure-requests` test that subresources are upgraded. The resource in the footer is the actual test.

**Comment by obi1kenobi** [comment]
Ah I see. Thank you for the clarification.

**Comment by lgarron** [comment]
Of course.

Also, hi!

**Comment by obi1kenobi** [comment]
Oh hey :) Didn't realize it was you! Also, impressive response time!
