### ISSUE TITLE
Add untrusted-root.badssl.com

### ISSUE THREAD

**Issue by davidben** [google/badssl.com#170]
I'd suggest generating some custom certificate chain, have untrusted-root.badssl.com serve it, and add a link somewhere to download the root it uses.

**Comment by lgarron** [comment]
Note: the commit above implemented the actual domain hosting, but the cert legwork for this was done in https://github.com/google/badssl.com/commit/effbe5eccbc6466683bdf0032b00ee7c3ae3f9b9#diff-b9ef2ef146678ad9bdcdb9fd53682806R44

**Comment by lgarron** [comment]
Man, it always turns out we had a bug for everything all along: #150.
