### ISSUE TITLE
Move badssl.com off google compute into AWS

### ISSUE THREAD

**Issue by marumari** [google/badssl.com#183]
We had talked about it a while back, but I believe we were going to move badssl.com into AWS.  I setup an Ubuntu 16.04 instance a while back, so we should probably move to that.  It lets us get the latest nginx and ciphers (aka CHACHA20-POLY1305).

The host, if you've forgotten, is:
`ec2-52-90-130-29.computer-1.amazonaws.com`

If you no longer want to move it there, let me know and I will shut down the EC2 instance.

**Comment by lgarron** [comment]
I don't feel strongly, but having it on Google Cloud has come in handy a few times (like yesterday when I needed to fiddle with the DNS to confirm a cert verification email).
Would you be alright with Google Cloud for now? I'll switch us over to a 16.04 box.

We can always move to AWS later if there are other benefits.

**Comment by marumari** [comment]
I don't have much skin in this particular game, other than finding the AWS toolchain to be somewhat less annoying than the Google Compute toolchain, which feels altogether too much like magic.

I'll go ahead and kill the AWS 16.04 instance once we've successfully moved to a GC 16.04 system.  :)

**Comment by lgarron** [comment]
> I'll go ahead and kill the AWS 16.04 instance once we've successfully moved to a GC 16.04 system. :)

Migrated!

**Comment by lgarron** [comment]
BTW you may want to update your SSH key at https://console.cloud.google.com/compute/metadata/sshKeys?project=mixed-content-test&organizationId=433637338589

The current key is *shudder* RSA.

**Comment by marumari** [comment]
Can you add april@pokeinthe.io to the project?  Right now I'm using my old account, and that sucks.  I do normally use ed25519 ssh keys.  :)

https://pokeinthe.io/about/  <-- at the bottom

**Comment by lgarron** [comment]
> Can you add april@pokeinthe.io to the project?

Done.

> https://pokeinthe.io/about/ <-- at the bottom

Okaaaaaaay, done. :-)

**Comment by lgarron** [comment]
> > Can you add april@pokeinthe.io to the project?
> Done.

Wit, did you mean as project editor, or just the SSH key?

**Comment by marumari** [comment]
Okay, I've gone ahead and terminated our EC2 instance.  (cc: @gene1wood)
